modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="tezt_dummi_mod"
version="1.0.0"
displayName="Tezt Dummi Mod"
credits="Made with Mcreator show them some love <3"
displayURL="https://mcreator.net"
authors="Tezt Dummi, Typin Man"
description='''
Poggers
'''

[[dependencies.tezt_dummi_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




