modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="tezt_dummi_mod"
version="1.0.0"
displayName="Tezt Dummi Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="nintu, MCreator"

[[dependencies.tezt_dummi_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




